      integer                                                           &
     & nh01,nh02,nh03,nh04,nh05,nh06,nh07,nh08,nh09,nh10,               &
     & nb01,nb02,nb03,nb04,nb05,nb06,nb07,nb08,nb09,nb10,               &
     &                                         ns09,ns10,               &
     & nt01,nt02,nt03,nt04,nt05,nt06,nt07,nt08,nt09,nt10,               &
     & nu01,nu02,nu03,nu04,nu05,nu06,nu07,nu08,nu09,nu10,               &
     & nd01,nd02,nd03,nd04,nd05,nd06,nd07,nd08,nd09,nd10,               &
     & ntbqs,ihgen_flag,dmsbeta_size
      common/bk05/                                                      &
     & nh01,nh02,nh03,nh04,nh05,nh06,nh07,nh08,nh09,nh10,               &
     & nb01,nb02,nb03,nb04,nb05,nb06,nb07,nb08,nb09,nb10,               &
     &                                         ns09,ns10,               &
     & nt01,nt02,nt03,nt04,nt05,nt06,nt07,nt08,nt09,nt10,               &
     & nu01,nu02,nu03,nu04,nu05,nu06,nu07,nu08,nu09,nu10,               &
     & nd01,nd02,nd03,nd04,nd05,nd06,nd07,nd08,nd09,nd10,               &
     & ntbqs,ihgen_flag,dmsbeta_size
!
      MINDEX dm_hmtnum,dm_hnfegp
      MINDEX dm_bmtnum,dm_bnfegp
      MINDEX dm_smtnum,dm_snfegp
      MINDEX dm_tmtnum,dm_tnfegp
!
      common/dmbk05/                                                    &
     & dm_hmtnum,dm_hnfegp,                                             &
     & dm_bmtnum,dm_bnfegp,                                             &
     & dm_smtnum,dm_snfegp,                                             &
     & dm_tmtnum,dm_tnfegp
