      character*16 istupd
      integer istrn,istupd_flag,                                        &
     &        ibelyt,miter,ipstpd,intsts,nodsts,intstn,                 &
     &        nodstn,jstrn,nddet,nsout01,nsout02,nsout03,nsout04,       &
     &        nsout05,nsout06,mporlk,lporlk,istrn_t,istrn_p
      real wrpang
      common/shlopt/istrn,istupd_flag,ibelyt,miter,wrpang,              &
     & ipstpd,intsts,nodsts,intstn,nodstn,jstrn,nddet,nsout01,          &
     & nsout02,nsout03,nsout04,nsout05,nsout06,mporlk,lporlk,           &
     & istrn_t,istrn_p
